name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          false
        if: succeeded() || failed()
      - shell: bash
        run: |
          false
        if: always()
